# Generated by Django 5.0.4 on 2024-04-19 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0002_alter_lesson_content'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LessonContent',
        ),
    ]
