# Generated by Django 5.0.4 on 2024-05-05 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0005_remove_lesson_completed_remove_quiz_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='image',
        ),
    ]
